import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import Company from "../models/Company.js";

const initialCompanies = [
  {
    companyName: "Amazon",
    logo: "📦",
    website: "https://amazon.com",
    careersPage: "https://amazon.jobs",
    headquarters: "Seattle, WA, USA",
    foundedYear: 1994,
    industry: "Product Based / E-Commerce & Cloud (AWS)",
    companySize: "1,500,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "2 Medium/Hard DSA Problems + Work Style Assessment (Leadership Principles)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Arrays & Hashing", "Trees & BST", "BFS/DFS Graphs", "Dynamic Programming", "Heap / Priority Queue"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 20,
      developmentWeightage: 15,
      aptitudeWeightage: 15,
    },
    resumeExpectations: {
      preferredProjects: ["Distributed Systems", "Cloud Application (AWS)", "E-Commerce Microservices"],
      preferredSkills: ["Java", "C++", "AWS", "OOP Design Patterns", "SQL"],
      requiredTechnologies: ["Java/C++", "REST APIs", "SQL / NoSQL"],
    },
    compensation: {
      internshipCTC: "₹80,000 - ₹1,20,000 / month",
      fresherCTC: "₹28 - ₹45 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "January", "February"],
    },
    resources: {
      preparationResources: ["NeetCode 150 - Amazon List", "Amazon Leadership Principles Guide", "LeetCode Amazon Tagged Problems"],
      officialLinks: ["https://amazon.jobs/en/teams/university-recruiting"],
    },
  },
  {
    companyName: "Google",
    logo: "🔍",
    website: "https://google.com",
    careersPage: "https://careers.google.com",
    headquarters: "Mountain View, CA, USA",
    foundedYear: 1998,
    industry: "Product Based / Internet & AI",
    companySize: "180,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "Google Online Challenge (2 Hard Algorithmic Problems)",
      technicalRounds: 5,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Advanced Graphs (Dijkstra, Segment Tree)", "Dynamic Programming", "Tries & Trees", "Advanced Binary Search", "Bitmask DP"],
      dsaWeightage: 70,
      coreSubjectsWeightage: 15,
      developmentWeightage: 10,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["High-Performance Computing", "Compiler / OS Simulator", "Machine Learning Pipeline"],
      preferredSkills: ["C++", "Python", "Go", "Algorithms", "Data Structures"],
      requiredTechnologies: ["C++/Java/Python", "Linux", "Data Structures"],
    },
    compensation: {
      internshipCTC: "₹1,00,000 - ₹1,50,000 / month",
      fresherCTC: "₹35 - ₹60 LPA",
    },
    timeline: {
      hiringMonths: ["July", "August", "September"],
    },
    resources: {
      preparationResources: ["Google Tech Dev Guide", "LeetCode Google Tagged", "CP-Algorithms"],
      officialLinks: ["https://careers.google.com/students/"],
    },
  },
  {
    companyName: "Microsoft",
    logo: "💻",
    website: "https://microsoft.com",
    careersPage: "https://careers.microsoft.com",
    headquarters: "Redmond, WA, USA",
    foundedYear: 1975,
    industry: "Product Based / Software & Azure Cloud",
    companySize: "220,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "Codility Assessment (3 Algorithmic Problems)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Linked Lists", "Arrays & Strings", "Trees & BST", "Backtracking", "Dynamic Programming"],
      dsaWeightage: 55,
      coreSubjectsWeightage: 25,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Full Stack Web App", "Azure Cloud Integration", "Desktop Application"],
      preferredSkills: ["C#", "C++", "Java", "Azure", "OOP"],
      requiredTechnologies: ["C#/C++/Java", "SQL"],
    },
    compensation: {
      internshipCTC: "₹80,000 - ₹1,00,000 / month",
      fresherCTC: "₹25 - ₹43 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "October"],
    },
    resources: {
      preparationResources: ["LeetCode Microsoft Tagged", "Microsoft Interview Experience Guide"],
      officialLinks: ["https://careers.microsoft.com/students/us/en"],
    },
  },
  {
    companyName: "Adobe",
    logo: "🎨",
    website: "https://adobe.com",
    careersPage: "https://adobe.com/careers",
    headquarters: "San Jose, CA, USA",
    foundedYear: 1982,
    industry: "Product Based / Creative Software",
    companySize: "29,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "2 DSA Problems + Core CS MCQs (OS, DBMS, CN)",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Trees & Graphs", "Dynamic Programming", "Recursion", "Strings", "OS & Memory Management"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 30,
      developmentWeightage: 10,
      aptitudeWeightage: 10,
    },
    resumeExpectations: {
      preferredProjects: ["Image / Graphics Processing", "Media Editor", "Web API Service"],
      preferredSkills: ["C++", "Java", "Object Oriented Design", "OS Fundamentals"],
      requiredTechnologies: ["C++/Java", "Data Structures"],
    },
    compensation: {
      internshipCTC: "₹75,000 - ₹1,00,000 / month",
      fresherCTC: "₹24 - ₹40 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September"],
    },
    resources: {
      preparationResources: ["Adobe SheCodes Archive", "LeetCode Adobe Tagged"],
      officialLinks: ["https://www.adobe.com/careers/university.html"],
    },
  },
  {
    companyName: "Atlassian",
    logo: "🔷",
    website: "https://atlassian.com",
    careersPage: "https://atlassian.com/careers",
    headquarters: "Sydney, Australia",
    foundedYear: 2002,
    industry: "Product Based / Developer Tools (Jira, Confluence)",
    companySize: "10,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "HackerRank (3 Medium/Hard Algorithmic Problems)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Arrays & Hashing", "Trees", "Graph Traversals", "Object-Oriented Design (OOD)", "System Design"],
      dsaWeightage: 45,
      coreSubjectsWeightage: 20,
      developmentWeightage: 25,
      aptitudeWeightage: 10,
    },
    resumeExpectations: {
      preferredProjects: ["Real-time Collaboration App", "Full Stack Microservice", "DevOps Pipeline Tool"],
      preferredSkills: ["Java", "React", "Node.js", "System Design", "Clean Code"],
      requiredTechnologies: ["Java/TypeScript", "REST APIs"],
    },
    compensation: {
      internshipCTC: "₹1,00,000 - ₹1,25,000 / month",
      fresherCTC: "₹50 - ₹80 LPA",
    },
    timeline: {
      hiringMonths: ["July", "August"],
    },
    resources: {
      preparationResources: ["Atlassian Values & Craft Assessment", "LeetCode Atlassian Tagged"],
      officialLinks: ["https://www.atlassian.com/company/careers/students"],
    },
  },
  {
    companyName: "Juspay",
    logo: "💳",
    website: "https://juspay.in",
    careersPage: "https://juspay.in/careers",
    headquarters: "Bengaluru, India",
    foundedYear: 2012,
    industry: "Product Based / FinTech Payments",
    companySize: "1,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "Hackathon / Tree & Graph Coding Challenge (Tree Of Space)",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: false,
    },
    preparation: {
      importantTopics: ["N-ary Trees & Locking Algorithms", "Multi-threading & Concurrency", "Graph Algorithms", "Functional Programming"],
      dsaWeightage: 60,
      coreSubjectsWeightage: 20,
      developmentWeightage: 20,
      aptitudeWeightage: 0,
    },
    resumeExpectations: {
      preferredProjects: ["Concurrent Distributed Locks", "Payment Gateway Integration", "High Throughput Server"],
      preferredSkills: ["C++", "Java", "Haskell / Functional", "Multi-threading"],
      requiredTechnologies: ["C++/Java", "Multi-threading"],
    },
    compensation: {
      internshipCTC: "₹40,000 - ₹80,000 / month",
      fresherCTC: "₹20 - ₹27 LPA",
    },
    timeline: {
      hiringMonths: ["September", "October", "February"],
    },
    resources: {
      preparationResources: ["Juspay Tree of Space Problem Tutorial", "Multi-threading C++ Guide"],
      officialLinks: ["https://juspay.in/careers"],
    },
  },
  {
    companyName: "Oracle",
    logo: "🔴",
    website: "https://oracle.com",
    careersPage: "https://oracle.com/careers",
    headquarters: "Austin, TX, USA",
    foundedYear: 1977,
    industry: "Product Based / Enterprise Database & Cloud",
    companySize: "140,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "2 DSA Problems + DBMS/SQL & Aptitude MCQs",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["DBMS & SQL Queries", "Arrays & Strings", "Trees", "Operating Systems", "Computer Networks"],
      dsaWeightage: 40,
      coreSubjectsWeightage: 40,
      developmentWeightage: 10,
      aptitudeWeightage: 10,
    },
    resumeExpectations: {
      preferredProjects: ["Database Management Engine", "SQL Query Parser", "Cloud Infrastructure App"],
      preferredSkills: ["Java", "SQL", "DBMS", "Operating Systems", "C++"],
      requiredTechnologies: ["SQL", "Java/C++"],
    },
    compensation: {
      internshipCTC: "₹50,000 - ₹75,000 / month",
      fresherCTC: "₹18 - ₹32 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "October"],
    },
    resources: {
      preparationResources: ["GeeksforGeeks Oracle Interview Archive", "SQL Query Practice Sheet"],
      officialLinks: ["https://www.oracle.com/corporate/careers/students-graduates/"],
    },
  },
  {
    companyName: "Goldman Sachs",
    logo: "🏛️",
    website: "https://goldmansachs.com",
    careersPage: "https://goldmansachs.com/careers",
    headquarters: "New York, NY, USA",
    foundedYear: 1869,
    industry: "Investment Banking & FinTech",
    companySize: "45,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "HackerRank: 2 DSA Problems + Math/Probability + CS MCQs + Advanced Aptitude",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Arrays & Dynamic Programming", "Math & Permutations", "Probability & Logic Puzzles", "Hashing", "Trees"],
      dsaWeightage: 45,
      coreSubjectsWeightage: 25,
      developmentWeightage: 10,
      aptitudeWeightage: 20,
    },
    resumeExpectations: {
      preferredProjects: ["Financial Trading Simulation", "Algorithmic Stock Analyzer", "Statistical Data Engine"],
      preferredSkills: ["C++", "Java", "Probability", "Algorithms", "Linear Algebra"],
      requiredTechnologies: ["C++/Java/Python"],
    },
    compensation: {
      internshipCTC: "₹1,00,000 - ₹1,20,000 / month",
      fresherCTC: "₹30 - ₹50 LPA",
    },
    timeline: {
      hiringMonths: ["July", "August"],
    },
    resources: {
      preparationResources: ["Goldman Sachs Aptitude & Puzzle Archive", "LeetCode Goldman Sachs Tagged"],
      officialLinks: ["https://www.goldmansachs.com/careers/students/programs/"],
    },
  },
  {
    companyName: "Walmart Global Tech",
    logo: "✳️",
    website: "https://walmartglobaltech.com",
    careersPage: "https://walmartglobaltech.com/careers",
    headquarters: "Bentonville, AR, USA",
    foundedYear: 1962,
    industry: "Product Based / Retail & E-Commerce Tech",
    companySize: "100,000+ Tech Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "Unstop / HackerEarth CodeHers or Campus OA (2 DSA Problems + MCQs)",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Arrays & Strings", "Trees & Graphs", "Dynamic Programming", "DBMS & SQL", "OOP Concepts"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 30,
      developmentWeightage: 10,
      aptitudeWeightage: 10,
    },
    resumeExpectations: {
      preferredProjects: ["Inventory Management System", "E-Commerce Backend", "Order Tracking Microservice"],
      preferredSkills: ["Java", "Spring Boot", "SQL", "Data Structures", "Microservices"],
      requiredTechnologies: ["Java", "SQL"],
    },
    compensation: {
      internshipCTC: "₹85,000 - ₹1,00,000 / month",
      fresherCTC: "₹24 - ₹35 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "March"],
    },
    resources: {
      preparationResources: ["Walmart CodeHers Contest Archive", "LeetCode Walmart Tagged"],
      officialLinks: ["https://careers.walmart.com/technology"],
    },
  },
  {
    companyName: "Uber",
    logo: "🚗",
    website: "https://uber.com",
    careersPage: "https://uber.com/careers",
    headquarters: "San Francisco, CA, USA",
    foundedYear: 2009,
    industry: "Product Based / Mobility & Logistics",
    companySize: "30,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "CodeSignal Challenge (4 Algorithmic Problems in 70 mins)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Graph Algorithms (Dijkstra, Shortest Path)", "Dynamic Programming", "Heaps & Priority Queues", "System Design"],
      dsaWeightage: 65,
      coreSubjectsWeightage: 15,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Real-time Geo Tracking App", "Ride Dispatching Simulation", "Distributed System"],
      preferredSkills: ["Go", "Java", "C++", "Kafka", "Redis"],
      requiredTechnologies: ["Go/Java/C++", "Distributed Systems"],
    },
    compensation: {
      internshipCTC: "₹1,20,000 - ₹1,60,000 / month",
      fresherCTC: "₹40 - ₹65 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September"],
    },
    resources: {
      preparationResources: ["CodeSignal General Coding Assessment Guide", "Uber Engineering Blog"],
      officialLinks: ["https://www.uber.com/us/en/careers/students/"],
    },
  },
  {
    companyName: "Flipkart",
    logo: "🛍️",
    website: "https://flipkart.com",
    careersPage: "https://flipkartcareers.com",
    headquarters: "Bengaluru, India",
    foundedYear: 2007,
    industry: "Product Based / E-Commerce",
    companySize: "30,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "Flipkart GRID Hackathon or Campus OA (2 DSA + MCQs)",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Machine Coding Round (OOD)", "Trees & Graphs", "Dynamic Programming", "Low Level Design"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 20,
      developmentWeightage: 25,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Machine Coding Parking Lot / Snake & Ladder", "E-Commerce Cart Engine", "Microservices"],
      preferredSkills: ["Java", "OOP Design Patterns", "Clean Architecture", "SQL"],
      requiredTechnologies: ["Java", "OOD Patterns"],
    },
    compensation: {
      internshipCTC: "₹60,000 - ₹1,00,000 / month",
      fresherCTC: "₹26 - ₹36 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "January"],
    },
    resources: {
      preparationResources: ["Flipkart Machine Coding Guide", "LeetCode Flipkart Tagged"],
      officialLinks: ["https://www.flipkartcareers.com/#!/job-list"],
    },
  },
  {
    companyName: "Zoho",
    logo: "🔴",
    website: "https://zoho.com",
    careersPage: "https://zoho.com/careers",
    headquarters: "Chennai, India",
    foundedYear: 1996,
    industry: "Product Based / SaaS Business Suite",
    companySize: "15,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "Round 1: C Programming & Aptitude MCQs",
      technicalRounds: 3, // Includes Round 2: Advanced Coding & Round 3: Design
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["C/C++ Basics & Pointers", "String Manipulation", "Matrix Operations", "Recursion", "OOD Machine Coding"],
      dsaWeightage: 40,
      coreSubjectsWeightage: 20,
      developmentWeightage: 20,
      aptitudeWeightage: 20,
    },
    resumeExpectations: {
      preferredProjects: ["Console Based Game (TicTacToe/Chess)", "SaaS Web Application", "C/C++ Memory Parser"],
      preferredSkills: ["C", "Java", "Data Structures", "Problem Solving"],
      requiredTechnologies: ["C/Java"],
    },
    compensation: {
      internshipCTC: "₹20,000 - ₹35,000 / month",
      fresherCTC: "₹6 - ₹12 LPA",
    },
    timeline: {
      hiringMonths: ["Throughout the year"],
    },
    resources: {
      preparationResources: ["Zoho Round 2 & Round 3 Question Bank", "GeeksforGeeks Zoho Archive"],
      officialLinks: ["https://www.zoho.com/careers/"],
    },
  },
  {
    companyName: "Intuit",
    logo: "📊",
    website: "https://intuit.com",
    careersPage: "https://intuit.com/careers",
    headquarters: "Mountain View, CA, USA",
    foundedYear: 1983,
    industry: "Product Based / Financial & Tax SaaS (TurboTax, QuickBooks)",
    companySize: "17,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "Intuit Augment / HackerRank Challenge (2 DSA + Systems)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Trees & Graphs", "Dynamic Programming", "System Design & Microservices", "Object-Oriented Design"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 20,
      developmentWeightage: 25,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Tax Calculator Microservice", "Financial Ledger Dashboard", "Full Stack Web App"],
      preferredSkills: ["Java", "React", "Node.js", "Spring Boot", "AWS"],
      requiredTechnologies: ["Java/TypeScript", "AWS"],
    },
    compensation: {
      internshipCTC: "₹80,000 - ₹1,10,000 / month",
      fresherCTC: "₹30 - ₹45 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September"],
    },
    resources: {
      preparationResources: ["LeetCode Intuit Tagged", "Intuit Craft Demonstration Guide"],
      officialLinks: ["https://www.intuit.com/careers/university/"],
    },
  },
  {
    companyName: "Salesforce",
    logo: "☁️",
    website: "https://salesforce.com",
    careersPage: "https://salesforce.com/careers",
    headquarters: "San Francisco, CA, USA",
    foundedYear: 1999,
    industry: "Product Based / Enterprise CRM & Cloud",
    companySize: "70,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Medium",
    interviewProcess: {
      onlineAssessment: "HackerRank OA (3 DSA Problems in 90 mins)",
      technicalRounds: 3,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Arrays & Strings", "Trees & BST", "Graphs", "DBMS & SQL", "OOP Concepts"],
      dsaWeightage: 55,
      coreSubjectsWeightage: 25,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["CRM Dashboard", "Cloud Multi-tenant Application", "REST API Engine"],
      preferredSkills: ["Java", "Apex", "React", "SQL", "Cloud Computing"],
      requiredTechnologies: ["Java/C++", "SQL"],
    },
    compensation: {
      internshipCTC: "₹75,000 - ₹95,000 / month",
      fresherCTC: "₹28 - ₹42 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September"],
    },
    resources: {
      preparationResources: ["Trailhead by Salesforce", "LeetCode Salesforce Tagged"],
      officialLinks: ["https://www.salesforce.com/company/careers/university-recruiting/"],
    },
  },
  {
    companyName: "NVIDIA",
    logo: "👁️",
    website: "https://nvidia.com",
    careersPage: "https://nvidia.com/careers",
    headquarters: "Santa Clara, CA, USA",
    foundedYear: 1993,
    industry: "Product Based / GPU Hardware, AI & Compute",
    companySize: "29,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "2 Algorithmic DSA Problems + C++ Memory & OS MCQs",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["C++ Pointers & Memory Optimization", "Operating Systems & Concurrency", "Arrays & Bit Manipulation", "Parallel Programming (CUDA intro)"],
      dsaWeightage: 45,
      coreSubjectsWeightage: 35,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["GPU Acceleration Shader / CUDA", "C++ Memory Allocator", "Deep Learning Model Optimization"],
      preferredSkills: ["C++", "CUDA", "Operating Systems", "Computer Architecture", "Python"],
      requiredTechnologies: ["C++", "OS & Architecture"],
    },
    compensation: {
      internshipCTC: "₹80,000 - ₹1,20,000 / month",
      fresherCTC: "₹30 - ₹55 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September", "October"],
    },
    resources: {
      preparationResources: ["C++ Deep Dive Notes", "NVIDIA Technical Blog"],
      officialLinks: ["https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/"],
    },
  },
  {
    companyName: "Apple",
    logo: "🍎",
    website: "https://apple.com",
    careersPage: "https://apple.com/careers",
    headquarters: "Cupertino, CA, USA",
    foundedYear: 1976,
    industry: "Product Based / Consumer Electronics & iOS OS",
    companySize: "160,000+ Employees",
    hiringStatus: "Selective",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "Coding OA (2 Hard DSA Problems + Systems)",
      technicalRounds: 5,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["C++ & Swift Fundamentals", "Operating Systems & Memory", "Trees & Graphs", "System Architecture"],
      dsaWeightage: 55,
      coreSubjectsWeightage: 25,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["iOS Mobile App (Swift)", "Low Level System Utility", "Embedded Device Software"],
      preferredSkills: ["Swift", "C++", "Objective-C", "OS Kernel", "Data Structures"],
      requiredTechnologies: ["Swift/C++"],
    },
    compensation: {
      internshipCTC: "₹90,000 - ₹1,30,000 / month",
      fresherCTC: "₹35 - ₹60 LPA",
    },
    timeline: {
      hiringMonths: ["August", "September"],
    },
    resources: {
      preparationResources: ["Apple Developer Documentation", "LeetCode Apple Tagged"],
      officialLinks: ["https://www.apple.com/careers/us/students.html"],
    },
  },
  {
    companyName: "Meta",
    logo: "♾️",
    website: "https://meta.com",
    careersPage: "https://metacareers.com",
    headquarters: "Menlo Park, CA, USA",
    foundedYear: 2004,
    industry: "Product Based / Social Media & Metaverse",
    companySize: "67,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "Meta Coding Assessment (2 Medium/Hard Problems in 45 mins)",
      technicalRounds: 4,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Top Meta 100 Tagged LeetCode", "Arrays & Binary Search", "Trees & Graph Traversals", "System Design"],
      dsaWeightage: 65,
      coreSubjectsWeightage: 15,
      developmentWeightage: 15,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Social Feed Engine", "Real-time Messaging System", "React Native Application"],
      preferredSkills: ["C++", "Python", "React", "Hack/PHP", "System Design"],
      requiredTechnologies: ["C++/Python/Java"],
    },
    compensation: {
      internshipCTC: "₹1,10,000 - ₹1,60,000 / month",
      fresherCTC: "₹40 - ₹70 LPA",
    },
    timeline: {
      hiringMonths: ["July", "August", "September"],
    },
    resources: {
      preparationResources: ["LeetCode Top Meta 100 List", "Meta Engineering Blog"],
      officialLinks: ["https://www.metacareers.com/students-and-grads/"],
    },
  },
  {
    companyName: "Netflix",
    logo: "🎬",
    website: "https://netflix.com",
    careersPage: "https://jobs.netflix.com",
    headquarters: "Los Gatos, CA, USA",
    foundedYear: 1997,
    industry: "Product Based / Streaming & Entertainment Tech",
    companySize: "13,000+ Employees",
    hiringStatus: "Selective",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Hard",
    interviewProcess: {
      onlineAssessment: "CodeSignal General Coding Challenge",
      technicalRounds: 5,
      hrRounds: 1,
      systemDesignRequired: true,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["High Scale Distributed Systems", "Concurrency & Multithreading", "Graphs & Trees", "Microservices Architecture"],
      dsaWeightage: 50,
      coreSubjectsWeightage: 20,
      developmentWeightage: 25,
      aptitudeWeightage: 5,
    },
    resumeExpectations: {
      preferredProjects: ["Video Streaming Server", "Distributed Cache System", "Microservices Pipeline"],
      preferredSkills: ["Java", "Node.js", "gRPC", "Kafka", "AWS"],
      requiredTechnologies: ["Java/TypeScript", "AWS"],
    },
    compensation: {
      internshipCTC: "₹1,20,000 - ₹1,70,000 / month",
      fresherCTC: "₹45 - ₹80 LPA",
    },
    timeline: {
      hiringMonths: ["September", "October"],
    },
    resources: {
      preparationResources: ["Netflix Tech Blog", "System Design Primer by Donne Martin"],
      officialLinks: ["https://jobs.netflix.com/emerging-talent"],
    },
  },
  {
    companyName: "Infosys",
    logo: "🔷",
    website: "https://infosys.com",
    careersPage: "https://infosys.com/careers",
    headquarters: "Bengaluru, India",
    foundedYear: 1981,
    industry: "Service Based / IT Services & Consulting",
    companySize: "300,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Easy",
    interviewProcess: {
      onlineAssessment: "HackWithInfy / InfyTQ (Aptitude + Basic Coding)",
      technicalRounds: 2,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Aptitude & Quantitative Reasoning", "Basic Data Structures (Arrays, Strings)", "SQL & DBMS Basics", "Java/Python Fundamentals"],
      dsaWeightage: 30,
      coreSubjectsWeightage: 30,
      developmentWeightage: 10,
      aptitudeWeightage: 30,
    },
    resumeExpectations: {
      preferredProjects: ["Web Application (HTML/CSS/JS)", "Student Management System", "Database Project"],
      preferredSkills: ["Java", "Python", "SQL", "HTML/CSS"],
      requiredTechnologies: ["Java/Python", "SQL"],
    },
    compensation: {
      internshipCTC: "₹15,000 - ₹25,000 / month",
      fresherCTC: "₹3.6 - ₹9.5 LPA (System Engineer / Specialist Programmer)",
    },
    timeline: {
      hiringMonths: ["Throughout the year", "August-December"],
    },
    resources: {
      preparationResources: ["InfyTQ Official Sample Papers", "PrepInsta Infosys Guide"],
      officialLinks: ["https://www.infosys.com/careers/"],
    },
  },
  {
    companyName: "TCS",
    logo: "🔵",
    website: "https://tcs.com",
    careersPage: "https://tcs.com/careers",
    headquarters: "Mumbai, India",
    foundedYear: 1968,
    industry: "Service Based / IT Services & Consulting",
    companySize: "600,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: false,
    fullTimeAvailable: true,
    difficultyLevel: "Easy",
    interviewProcess: {
      onlineAssessment: "TCS NQT (National Qualifier Test): Numerical, Verbal, Reasoning + 2 Coding Problems",
      technicalRounds: 1,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Aptitude & Logical Reasoning", "Basic C/Python Syntax", "Arrays & Strings", "Basic SQL"],
      dsaWeightage: 25,
      coreSubjectsWeightage: 25,
      developmentWeightage: 10,
      aptitudeWeightage: 40,
    },
    resumeExpectations: {
      preferredProjects: ["Academic Web Project", "Basic Database System"],
      preferredSkills: ["C", "Python", "Java", "SQL"],
      requiredTechnologies: ["C/Python/Java"],
    },
    compensation: {
      internshipCTC: "N/A",
      fresherCTC: "₹3.36 - ₹11.5 LPA (Ninja / Digital / Prime Roles)",
    },
    timeline: {
      hiringMonths: ["August", "September", "February"],
    },
    resources: {
      preparationResources: ["TCS NQT Preparation Test Series", "PrepInsta TCS NQT"],
      officialLinks: ["https://www.tcs.com/careers"],
    },
  },
  {
    companyName: "Accenture",
    logo: "🟣",
    website: "https://accenture.com",
    careersPage: "https://accenture.com/careers",
    headquarters: "Dublin, Ireland",
    foundedYear: 1989,
    industry: "Service Based / IT & Management Consulting",
    companySize: "700,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: true,
    fullTimeAvailable: true,
    difficultyLevel: "Easy",
    interviewProcess: {
      onlineAssessment: "Cognitive & Technical Assessment + Coding Round + Communication Assessment",
      technicalRounds: 1,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Cognitive Ability", "Pseudocode & MS Office Basics", "Basic DSA (Arrays, Strings)", "Communication Skills"],
      dsaWeightage: 25,
      coreSubjectsWeightage: 25,
      developmentWeightage: 15,
      aptitudeWeightage: 35,
    },
    resumeExpectations: {
      preferredProjects: ["Web Portal", "Basic Management System"],
      preferredSkills: ["Python", "Java", "SQL", "Communication"],
      requiredTechnologies: ["Python/Java"],
    },
    compensation: {
      internshipCTC: "₹20,000 - ₹30,000 / month",
      fresherCTC: "₹4.5 - ₹11 LPA (ASE / FSE Roles)",
    },
    timeline: {
      hiringMonths: ["August", "September", "October"],
    },
    resources: {
      preparationResources: ["Accenture Assessment Pattern Guide", "PrepInsta Accenture"],
      officialLinks: ["https://www.accenture.com/in-en/careers"],
    },
  },
  {
    companyName: "Capgemini",
    logo: "🔷",
    website: "https://capgemini.com",
    careersPage: "https://capgemini.com/careers",
    headquarters: "Paris, France",
    foundedYear: 1967,
    industry: "Service Based / IT Consulting",
    companySize: "350,000+ Employees",
    hiringStatus: "Actively Hiring",
    internshipAvailable: false,
    fullTimeAvailable: true,
    difficultyLevel: "Easy",
    interviewProcess: {
      onlineAssessment: "Pseudocode Test + English Communication + Game-Based Aptitude + Coding Round",
      technicalRounds: 1,
      hrRounds: 1,
      systemDesignRequired: false,
      behavioralInterview: true,
    },
    preparation: {
      importantTopics: ["Game-based Aptitude Logic", "Pseudocode Debugging", "Basic Strings & Math Coding", "DBMS"],
      dsaWeightage: 25,
      coreSubjectsWeightage: 25,
      developmentWeightage: 15,
      aptitudeWeightage: 35,
    },
    resumeExpectations: {
      preferredProjects: ["College Project", "Web Application"],
      preferredSkills: ["Java", "C++", "SQL", "Logical Reasoning"],
      requiredTechnologies: ["Java/C++"],
    },
    compensation: {
      internshipCTC: "N/A",
      fresherCTC: "₹4.0 - ₹7.5 LPA",
    },
    timeline: {
      hiringMonths: ["September", "October"],
    },
    resources: {
      preparationResources: ["Capgemini Game Based Aptitude Practice", "PrepInsta Capgemini"],
      officialLinks: ["https://www.capgemini.com/in-en/careers/"],
    },
  },
];

export const seedCompanyDatabase = async () => {
  try {
    const uri = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/careeros";
    await mongoose.connect(uri);
    console.log("MongoDB Connected for Seeding Company Data...");

    for (const compData of initialCompanies) {
      await Company.findOneAndUpdate(
        { companyName: compData.companyName },
        compData,
        { upsert: true, new: true }
      );
    }

    console.log(`Successfully seeded ${initialCompanies.length} companies into MongoDB!`);
    await mongoose.disconnect();
  } catch (error) {
    console.error("Error seeding companies:", error.message);
  }
};

// Run script if executed directly
if (process.argv[1]?.includes("seedCompanies.js")) {
  seedCompanyDatabase();
}
